{{- if eq .Values.kind "Deployment" }}
{{- if .Values.deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
{{ include "fluentd-elasticsearch.labels" . | indent 4 }}
  name: {{ include "fluentd-elasticsearch.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fluentd-elasticsearch.fullname" . }}
  minReplicas: {{ .Values.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployment.autoscaling.maxReplicas }}
  metrics:
{{- with .Values.deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
{{- end }}
{{- with .Values.deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
{{- end }}
{{- end }}
{{- end }}
